// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int numberOfRuns = Integer.parseInt(args[0]);
		int aboveHalf = 0, belowHalf = 0;
		
		// Generates and sorts Math.random a number of times equal to the input
		for (int i = 0; i < numberOfRuns; i++) {
			if (Math.random() > 0.5) {
				aboveHalf++;
			} else {
				belowHalf++;
			}
		}
		System.out.printf("> 0.5:  %d times%n<= 0.5: %d times%n", aboveHalf, belowHalf);
		// Checks if random was lower than or equal to 0.5 at least once, needed to calculate the ratio
		if (belowHalf != 0) {
			double ratio = (double) aboveHalf / belowHalf;
			System.out.println("Ratio:  " + ratio);
		}
	}
}
